### ISSUE TITLE
不支持 server.servlet.context-path 属性

### ISSUE THREAD

**Issue by zijun-hiwintech** [Halfmoonly/feignx-plugin#17]
项目定义了server.servlet.context-path属性, 无法有效跳转

![Image](https://github.com/user-attachments/assets/69bd067c-10f8-486c-b685-fa8714f855aa)

**Comment by TristeTulip** [comment]
这个支持的, 我试了 在 被调用方设置 server.servlet.context-path,可以支持的 , 需要调用方写全路径,希望作者能改进把

![Image](https://github.com/user-attachments/assets/956be677-91f0-4549-97aa-e38a54ce26ed)

**Comment by zpj80231** [comment]
我也复现了，如果模块有指定context-path我这也不支持识别和跳转。项目采用nacos配置。（当然，如果feign和项目都没有指定context-path的话是没问题的）

### 出现问题的截图

- 直接在url总写全路径，不支持
<img width="444" alt="Image" src="https://github.com/user-attachments/assets/7babd22d-b839-464d-966b-467eac9b4b68" />
 
- 使用 @FeignClient 的 path，不支持
<img width="677" alt="Image" src="https://github.com/user-attachments/assets/13cbb16f-7124-481d-ac7f-957003878b16" />

### 出现问题的配置
这是我的配置：
我在本地添加了配置文件，指定了context-path，配置文件如下
- application-local.yml ：
```
server:
  port: 8400
  servlet:
    context-path: /inner-api
    encoding:
      charset: utf-8
```
- bootstrap.yml
```
spring:
  application:
    name: momomo-i
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: @nacos.namespace@
        server-addr: @nacos.server-addr@ 
      config:
        server-addr: @nacos.config.server-addr@
        namespace: @nacos.config.namespace@
        file-extension: yaml
```

### 项目环境

- MacOS 15.4.1 (24E263)
- IntelliJ IDEA 2025.1.3 (Ultimate Edition)
- FeignClient Assistant 5.6.4.0
